### ISSUE TITLE
unexpected error in Geonode -> SSLError: bad handshake

### ISSUE THREAD

**Issue by wimpeelaerts** [GeoNode/gsimporter#5]
Hi guy's, 

I was debugging this component for some time so I thought it would be nice to share my findings. 
The issue I had was an unexpected error when uploading layers in the Geonode platform.

Taking a closer look it appeared to be a SSL issue. 

Setup:
Geonode (Docker compose) behind a proyx allowing only https traffic.
When uploading layers the upload/upload.py component uses te gn-gsimporter to do the work.
This component communicates with GeoServer located at  'LOCATION': 'http://geoserver:8080/geoserver/', so within the Docker network over http. This is correct and Geoserver responds as expeted. 

Some calls went well, but some failed. 
eg: get_progress, reload, ...
I found out that at some places the service_url was not used but the URL was build up of the response from an earlier call (by replacing netloc). 
eg:
```console
def get_progress(self):
            _progress = urlparse(self.progress)
            _url = urlparse(self._getuploader().client.url())
            _progress = _progress._replace(netloc=_url.netloc).geturl()
```
This is no issue if all is in http or in https. In my case (internal traffic http, external traffic https) it caused the component to communicate with Geoserver over http**s**://geoserver:8080/geoserver/ because the scheme was not replaced.
The component got the https scheme from the Proxy Base URL setting in Geoserver.

```console
_progress ##########
ParseResult(scheme=u'https', netloc=u'geonode.ggg.be:443', path=u'/geoserver/rest/imports/20/tasks/0/progress', params='', query='', fragment='')
_url #########
ParseResult(scheme='http', netloc='geoserver:8080', path='/geoserver/rest', params='', query='', fragment='')
_progress#########
https://geoserver:8080/geoserver/rest/imports/20/tasks/0/progress
```
Also noticed this in reload which makes use of:  def _url(self, spec, *parts)

I tackled the issue for the Geonode platform by removing the Proxy Base URL parameter, but this  is not an ideal fix. 

Best Regards

**Comment by hummeltech** [comment]
@wimpeelaerts Try out the fix here: #6 
Hopefully that resolves the issue you were having as well.
